services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    depends_on:
      - database
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "8501:8501"

